### ISSUE TITLE
Severe: Can't select or Join a room

### ISSUE THREAD

**Issue by maps101** [info442-sp19-undefined/hw7#17]
While the first page is accessible, the buttons that lead to other parts of the site are broken links. The first leads to https://info442-sp19-undefined.github.io/JoinRoom and the second lead to https://info442-sp19-undefined.github.io/Settings, both of which throw error 404.

To reproduce:
1. Follow link on github: https://info442-sp19-undefined.github.io/
2. Select either button "Join a Room" or "New Room"

**Comment by bbasinsk** [comment]
https://levelup.gitconnected.com/deploying-a-create-react-app-with-routing-to-github-pages-f386b6ce84c2
>By utilising react-router-dom’s HashRouter we don’t have to worry about getting a 404 error on page refresh.

**Comment by jacklchang** [comment]
https://info442-sp19-undefined.github.io/hw7/ 
We fixed this!
