### ISSUE TITLE
Minor: No input validation / stuck on categories page

### ISSUE THREAD

**Issue by bbasinsk** [info442-sp19-undefined/hw7#18]
I also had the same issue with the [buttons not working straight away](https://github.com/info442-sp19-undefined/hw7/issues/17), however I was able to get your site to run locally by `cloning` and running `npm start`.

## Issue:
You can attempt to create a room with less than one icebreaker questions. The **settings** page will still let you create the room. However, once you create that room and redirect to the **categories** page (as seen below), the user gets stuck as none of the buttons do anything. There is also no back button to go back to update the number of questions.

![image](https://user-images.githubusercontent.com/13632637/59243393-ae8f7980-8bc4-11e9-86b4-00e150465cbf.png)

## Steps to reproduce
1. Clone repo
2. Run `npm start`
3. Open `localhost:3000`
4. Click on **New Room**
5. Enter an **Organizer Name** and **0 questions**
6. None of the category buttons work and **Go to Room** doesn't work.

**Comment by jacklchang** [comment]
If the organizer has no questions, then there should not be any questions to display no matter the category. Additionally, the Go To Room button should not work in this case because there is no game to play with no questions. Thus, we decided that this is not a major issue.
